export const ErrorList = {
  ENTRY_ACCOUNT_CATEGORY_ALREADY_EXISTS: "category_exists",
  ["INVALID USER"]: "invalid_user",
  ["BadRequestException: NO ITENS FOUND"]: "items_not_found",
  ["Missing process handler for job type create-entry-account-organizations-report-job"]:
    "missing_process_handler",
  ["TOKEN WITHOUT AGGREGATOR_ID"]: "token_without_aggregator_id",
  ["CAN ONLY BE DELETED BY ORGANIZATION"]: "can_only_be_deleted_by_organization",
  ["SAME_TO_AND_FROM_BALANCE"]: "same_to_and_from_balance",
  ["LICENSE NOT FOUND"]: "license_not_found",
  ["CANNOT DELETE LICENSE WITH MERCHANTS"]: "cannot_delete_license_with_merchants",
  ["NO BANKS SELECTED"]: "no_banks_selected",
  ["BANK BEING USED FOR CASH IN"]: "disable_bank_being_used_for_cash_in",
  ["BANK BEING USED FOR CASH OUT"]: "disable_bank_being_used_for_cash_out",
  ["BANK BEING USED FOR FASTPIX IN"]: "disable_bank_being_used_for_fastpix_in",
  ["BANK BEING USED"]: "disable_bank_being_used",
  ["cellphone must be a valid phone number"]: "phone_must_be_a_valid_phone_number",
  ["Forbidden resource"]: "forbidden_resource",
  ["is possible to create report from max 30 days"]: "is_possible_to_create_report_from_max_30_days",
  ["DOCUMENT ALREADY ON BLACKLIST"]: "document_already_on_blacklist",
  ["CNPJ inválido"]: "invalid_cnpj",
  ["CPF already exists"]: "cpf_already_exists",
  ["REASON ALREADY CREATED"]: "reason_already_created",
};
